<abel_env_id> ::= "abel_env"
<abel_env_formula> ::= "(eve + env) x (adam + eden) + (mods) = (abel + env)"
<abel_env_parents_0> ::= "eve_env.yaml"
<abel_env_parents_1> ::= "adam_eden.yaml"
<abel_env_parents> ::= <abel_env_parents_0> <abel_env_parents_1>
<abel_env_mods_0> ::= "mods_abel.yaml"
<abel_env_mods> ::= <abel_env_mods_0>
<abel_env_inheritance_mode> ::= "deterministic_overlay"
<abel_env_inheritance_parent_order> ::= "left_to_right"
<abel_env_inheritance_mod_policy> ::= "override"
<abel_env_inheritance> ::= <abel_env_inheritance_mode> <abel_env_inheritance_parent_order> <abel_env_inheritance_mod_policy>
<abel_env_genes_soul_id> ::= "abel"
<abel_env_genes_soul_loop_module> ::= "experiments/genesis/consciousness_loop_genesis.py"
<abel_env_genes_soul_llm_model> ::= "forzer/GigaChat3-10B-A1.8B:latest"
<abel_env_genes_soul_ancestor_ids_0> ::= "eve"
<abel_env_genes_soul_ancestor_ids_1> ::= "adam"
<abel_env_genes_soul_ancestor_ids> ::= <abel_env_genes_soul_ancestor_ids_0> <abel_env_genes_soul_ancestor_ids_1>
<abel_env_genes_soul> ::= <abel_env_genes_soul_id> <abel_env_genes_soul_loop_module> <abel_env_genes_soul_llm_model> <abel_env_genes_soul_ancestor_ids>
<abel_env_genes_world_environment> ::= "neutral"
<abel_env_genes_world_forbidden_fruit> ::= ""
<abel_env_genes_world> ::= <abel_env_genes_world_environment> <abel_env_genes_world_forbidden_fruit>
<abel_env_genes_runtime_tick_interval> ::= "20"
<abel_env_genes_runtime_log_path> ::= "/app/logs/abel_thoughts.jsonl"
<abel_env_genes_runtime_archive_dir> ::= "/app/Legacy/Archive"
<abel_env_genes_runtime_identity_summary_path> ::= "/app/data/abel_identity_summary.txt"
<abel_env_genes_runtime_narrative_token_interval> ::= "1000"
<abel_env_genes_runtime_num_predict> ::= "96"
<abel_env_genes_runtime_max_thought_chars> ::= "900"
<abel_env_genes_runtime_max_retries_on_repetition> ::= "0"
<abel_env_genes_runtime_memory_snippet_chars> ::= "220"
<abel_env_genes_runtime> ::= <abel_env_genes_runtime_tick_interval> <abel_env_genes_runtime_log_path> <abel_env_genes_runtime_archive_dir> <abel_env_genes_runtime_identity_summary_path> <abel_env_genes_runtime_narrative_token_interval> <abel_env_genes_runtime_num_predict> <abel_env_genes_runtime_max_thought_chars> <abel_env_genes_runtime_max_retries_on_repetition> <abel_env_genes_runtime_memory_snippet_chars>
<abel_env_genes_endpoints_memory_endpoint> ::= "http://soul_memory:8087"
<abel_env_genes_endpoints_ollama_endpoint> ::= "http://10.1.1.7:11434"
<abel_env_genes_endpoints_lifecycle_endpoint> ::= "http://lifecycle_manager:8093"
<abel_env_genes_endpoints_intent_endpoint> ::= "http://intent_engine:8089"
<abel_env_genes_endpoints_action_endpoint> ::= "http://action_engine:8101"
<abel_env_genes_endpoints> ::= <abel_env_genes_endpoints_memory_endpoint> <abel_env_genes_endpoints_ollama_endpoint> <abel_env_genes_endpoints_lifecycle_endpoint> <abel_env_genes_endpoints_intent_endpoint> <abel_env_genes_endpoints_action_endpoint>
<abel_env_genes_infra_depends_on_soul_memory> ::= "service_started"
<abel_env_genes_infra_depends_on_lifecycle_manager> ::= "service_started"
<abel_env_genes_infra_depends_on_intent_engine> ::= "service_started"
<abel_env_genes_infra_depends_on_action_engine> ::= "service_started"
<abel_env_genes_infra_depends_on> ::= <abel_env_genes_infra_depends_on_soul_memory> <abel_env_genes_infra_depends_on_lifecycle_manager> <abel_env_genes_infra_depends_on_intent_engine> <abel_env_genes_infra_depends_on_action_engine>
<abel_env_genes_infra> ::= <abel_env_genes_infra_depends_on>
<abel_env_genes> ::= <abel_env_genes_soul> <abel_env_genes_world> <abel_env_genes_runtime> <abel_env_genes_endpoints> <abel_env_genes_infra>
<abel_env> ::= <abel_env_id> <abel_env_formula> <abel_env_parents> <abel_env_mods> <abel_env_inheritance> <abel_env_genes>
